In [ ]:
students ={}
try:
    while True:
        print("1.Add marks of the student:")
        print("2.Check student result:")

        choice = input("Enter your choice:")

        if choice == '1':
            print("Enter 
except ValueError:
    print("Error!)

In [1]:
students={
    "name":"Rahul",
    "marks":[78,82,90],
    "passed":True
}
print(students)

{'name': 'Rahul', 'marks': [78, 82, 90], 'passed': True}


In [ ]:
def add_marks(students,marks):
    name = input("Enter name of student:")
    marks = input("Enter marks:")
    students['name'] = 

In [8]:
print("Python is working!")
marks=[20,30,40,60]
print(marks)
print(marks[0])
print(marks[3])

Python is working!
[20, 30, 40, 60]
20
60


In [9]:
total = 0
for m in marks:
    total += m
print(total)

150


In [10]:
count = len(marks)
avg = total/count
print(avg)

37.5


In [18]:
mark = [20,30,40,50,60]

total = 0

for m in mark:
    total += m
average = total/len(mark)
print(average)
if average >=60:
    print("Passed")
else:
    print("Failed")

mark.pop()
for m in mark:
    total += m
average = total/len(mark)
print(average)
if average >=60:
    print("Passed")
else:
    print("Failed")

40.0
Failed
85.0
Passed


In [15]:
mark

[20, 30, 40, 50]

In [17]:
mark.append(100)
print(mark)
mark.pop()
for m in mark:
    total += m
average = total/len(mark)
print(average)

[20, 30, 40, 50, 100, 100]
116.0


In [24]:
mark

[20, 30, 40, 50]

In [22]:
def average_marks(mark):
    total = 0
    for m in mark:
        total += m
    average = total/len(mark)
    print("Average:",average)

In [23]:
average_marks(mark)

Average: 35.0


In [27]:
data = ["45","78","",None,"90","fail"]
cleaned = []
for items in data:
    if items is None:
        continue
    item = str(items).strip()
    if item.isdigit():
        cleaned.append(items)
print(cleaned)

['45', '78', '90']


In [35]:
import numpy as np
A = np.array([1,4,3,2])
print(A)
print(A+10)
print(A*2)
print(np.mean(A))
print(np.std(A))

[1 4 3 2]
[11 14 13 12]
[2 8 6 4]
2.5
1.118033988749895


In [34]:
B = A+5
print(B)

[6 9 8 7]


In [38]:
x = np.array([1,2,3,4,5])
y = np.array([2,5,6,9,10])
corr = np.corrcoef(x,y)
print(corr)

[[1. 1.]
 [1. 1.]]


In [48]:
scores =np.array([56,67,78,89,90])
new_scores = scores+3
print("scores:",scores)
print("new scores:",new_scores)
print("mean:",np.mean(new_scores))
print("std:",np.std(new_scores))
for m in new_scores:
    if m>np.mean(new_scores):
        print(m,"")

scores: [56 67 78 89 90]
new scores: [59 70 81 92 93]
mean: 79.0
std: 13.038404810405298
81 
92 
93 
